# Generated by Django 2.0 on 2019-11-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0002_auto_20191104_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=17),
        ),
    ]
