# Generated by Django 2.0 on 2019-11-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0003_auto_20191118_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
