# Generated by Django 2.0 on 2019-11-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0004_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('latitude', models.CharField(max_length=250)),
                ('longitude', models.CharField(max_length=250)),
                ('products', models.ManyToManyField(to='gram.Product')),
            ],
        ),
    ]
