# Generated by Django 2.0 on 2019-11-06 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0005_gram_product_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='gram',
            name='current_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gram.Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gram',
            name='stores',
            field=models.ManyToManyField(to='gram.Store'),
        ),
    ]
