# Generated by Django 2.0 on 2019-11-08 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0006_auto_20191106_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gram',
            name='current_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gram.Location'),
        ),
    ]
